version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file: .env
    expose:
       - "5432"
  web:
    build: .
    env_file: .env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
